apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-services
spec:
  params:
    - name: git-url
      default: https://github.com/redhat-na-ssa/workshop_camel_workspace.git
      description: Your Git repo
      type: string
    - name: module-name
      default: 'module-04'
      description: 'Module directory Name (defaults to module-04)'      
      type: string
    - name: service-name
      default: 'customer-service'
      description: 'Service Name (maven project directory, one of: customer-service | customer-connector | order-connector)'      
      type: string
    - name: registry-repo
      default: 'user1-camel'
      description: Registry Repository name (if using quay.io it should be your username, if using Openshift it should be the project/namespace name)
      type: string
    - name: maven-mirror-url
      default: https://repo1.maven.org/maven2/
      description: Maven Mirror Repo URL
      type: string
    - name: clone-subdir
      default: code-repo
      description: sub-directory where the repo will be cloned into
      type: string
    - name: git-revision
      default: solution
      description: 'branch, tag or revision. Defaults to main.'
      type: string
    - name: registry-url
      default: image-registry.openshift-image-registry.svc.cluster.local:5000
      description: Container Image Registry URL (default to Openshift internal registry)
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: $(params.clone-subdir)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-package
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - clean
            - package
            - '-DskipTests'
            - '-e'
            - '-B'
            - '-Dmaven.repo.local=$(workspaces.source.path)/.m2'
            - '-Dquarkus.openshift.namespace=user1-camel'
            - '-Dquarkus.openshift.name=$(params.service-name)'
            - '-Dquarkus.kubernetes.deploy=false'
            - '-Dquarkus.container-image.build=false'
            - '-Dquarkus.container-image.group=user1-camel'
            - '-Dquarkus.container-image.builder=openshift'
            - '-Dquarkus.openshift.deployment-kind=deployment'
            - '-Dquarkus.openshift.replicas=1'
            - '-Dquarkus.openshift.part-of=$(params.service-name)'
            - '-Dquarkus.openshift.route.expose=true'
            - '-Dquarkus.openshift.route.target-port=https'
            - '-Dquarkus.openshift.route.tls.termination=passthrough'
            - '-Dquarkus.openshift.route.tls.insecure-edge-termination-policy=None'
            - '-Dquarkus.openshift.labels.app."openshift.io/runtime"=quarkus'
            - '-Dquarkus.openshift.annotations."app.openshift.io/vcs-url"=$(params.git-url)'
            - '-Dquarkus.openshift.annotations."app.openshift.io/vcs-ref"=$(params.git-revision)'
            - '-Dquarkus.openshift.annotations."prometheus.io/scrape"="true"'
            - '-Dquarkus.openshift.annotations."prometheus.io/path"=/q/metrics'
            - '-Dquarkus.openshift.annotations."prometheus.io/port"="8080"'
            - '-Dquarkus.openshift.annotations."prometheus.io/scheme"=http'
            # - '-Dquarkus.openshift.annotations."app.openshift.io/connects-to"="service-name"'
            - '-Dquarkus.openshift.readiness-probe.http-action-port=8080'
            - '-Dquarkus.openshift.readiness-probe.http-action-path=/q/health/ready'
            - '-Dquarkus.openshift.readiness-probe.http-action-scheme=http'
            - '-Dquarkus.openshift.resources.requests.cpu=0.5'
            - '-Dquarkus.openshift.resources.requests.memory=256Mi'
            - '-Dquarkus.openshift.resources.limits.cpu=2'
            - '-Dquarkus.openshift.resources.limits.memory=1Gi'
            # - '-Dquarkus.openshift.readiness-probe.initial-delay'
            # - '-Dquarkus.openshift.readiness-probe.period'
            # - '-Dquarkus.openshift.readiness-probe.timeout'
        - name: CONTEXT_DIR
          value: $(params.clone-subdir)/$(params.module-name)/$(params.service-name)
        - name: MAVEN_MIRROR_URL
          value: $(params.maven-mirror-url)
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: image-build
      params:
        - name: IMAGE
          value: >-
            $(params.registry-url)/$(params.registry-repo)/$(params.service-name):$(tasks.git-clone.results.commit)
        # - name: BUILDER_IMAGE
        #   value: >-
        #     registry.redhat.io/rhel8/buildah
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm
        - name: CONTEXT
          value: $(params.clone-subdir)/$(params.module-name)/$(params.service-name)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - maven-package
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: image-tag
      params:
        - name: srcImageURL
          value: >-
            docker://$(params.registry-url)/$(params.registry-repo)/$(params.service-name):$(tasks.git-clone.results.commit)
        - name: destImageURL
          value: >-
            docker://$(params.registry-url)/$(params.registry-repo)/$(params.service-name):latest
      runAfter:
        - image-build
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: image-urls-cm

    - name: deploy-app
      params:
        - name: SCRIPT
          value: |
            ls -la $(params.clone-subdir)/$(params.module-name)/$(params.service-name)/target/kubernetes/
            oc apply -f $(params.clone-subdir)/$(params.module-name)/$(params.service-name)/target/kubernetes/openshift.yml
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
      runAfter:
        - image-tag

  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: image-urls-cm