---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-quarkus
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 256Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
