- rest:
    get:
    - id: "getCustomers"
      path: "/customers"
      description: "Gets a list of all `Customer` entities."
      produces: "application/json"
      to: "direct:getCustomers"
    - id: "getCustomer"
      path: "/customers/{customerId}"
      description: "Gets the details of a single instance of a `Customer`."
      produces: "application/json"
      param:
      - dataType: "string"
        description: "A unique identifier for a `Customer`."
        name: "customerId"
        required: true
        type: "path"
      to: "direct:getCustomer"
    post:
    - id: "createCustomer"
      path: "/customers"
      description: "Creates a new instance of a `Customer`."
      consumes: "application/json"
      param:
      - description: "A new `Customer` to be created."
        name: "body"
        required: true
        type: "body"
      to: "direct:createCustomer"
    put:
    - id: "updateCustomer"
      path: "/customers/{customerId}"
      description: "Updates an existing `Customer`."
      consumes: "application/json"
      param:
      - dataType: "string"
        description: "A unique identifier for a `Customer`."
        name: "customerId"
        required: true
        type: "path"
      - description: "Updated `Customer` information."
        name: "body"
        required: true
        type: "body"
      to: "direct:updateCustomer"
    delete:
    - id: "deleteCustomer"
      path: "/customers/{customerId}"
      description: "Deletes an existing `Customer`."
      param:
      - dataType: "string"
        description: "A unique identifier for a `Customer`."
        name: "customerId"
        required: true
        type: "path"
      to: "direct:deleteCustomer"
